[tool.poetry]
name = "galaxy"
version = "22.01.dev0"
description = "Galaxy is an open, web-based platform for accessible, reproducible, and transparent computational research."
authors = ["Galaxy Contributors"]
license = "AFL-3.0"
readme = "README.rst"
homepage = "https://galaxyproject.org/"
repository = "https://github.com/galaxyproject/galaxy/"
documentation = "https://docs.galaxyproject.org/"

[[tool.poetry.source]]
name = "galaxyproject"
url = "https://wheels.galaxyproject.org/simple"

[tool.poetry.dependencies]
aiofiles = "*"
async-generator = {version = "*", python = "~3.6"}
async-exit-stack = {version = "*", python = "~3.6"}
Babel = "*"
bdbag = "*"
Beaker = "1.11.0"
bioblend = "*"
bleach = "*"
boltons = "*"
boto = "*"
bx-python = "*"
celery = "*"
Cheetah3 = "!=3.2.6.post2"  # yanked release, https://github.com/python-poetry/poetry/issues/2453
cloudauthz = "==0.6.0"
cloudbridge = "*"
contextvars = {version = "*", python = "~3.6"}
circus = "*"
cwltool = "==3.1.20211107152837"
cwl-utils = ">=0.13"
dictobj = "*"
docutils = "!=0.17, !=0.17.1"
edam-ontology = "*"
Fabric3 = "*"
fastapi = ">=0.68.2, !=0.69.0, !=0.70.0"  # https://github.com/tiangolo/fastapi/issues/4041
fastapi-utils = "*"
fs = "*"
future = "*"
galaxy_sequence_utils = "*"
gxformat2 = "*"
h5py = "==3.1.0"  # Last version compatible with python 3.6. Also adding this constraint speeds up poetry resolution immensely
isa-rwval = "*"
kombu = "*"
lagom = "*"
Mako = "*"
Markdown = "*"
MarkupSafe = "*"
Mercurial = "*"
mrcfile = "*"
nodeenv = "*"
nose = "*"
numpy = "*"
paramiko = "*"
Parsley = "*"
Paste = "*"
psutil = "*"
pulsar-galaxy-lib = ">=0.14.13"
pycryptodome = "*"
pykwalify = "*"
pyparsing = "*"
pysam = "*"
python = "^3.6.1"  # required by fastapi
python-multipart = "*"  # required to support form parsing in FastAPI/Starlette
pyuwsgi = "*"
PyYAML = "*"
refgenconf = ">=0.12.0"
requests = "*"
Routes = "*"
social-auth-core = {version = "==4.0.3", extras = ["openidconnect"]}
sortedcontainers = "*"
SQLAlchemy = ">=1.4.25,<2"
sqlalchemy-migrate = "*"
sqlitedict = "*"
sqlparse = "*"
starlette = "*"
starlette-context = {version = "*", python = ">=3.7"}
svgwrite = "*"
tifffile = "<=2020.9.3"  # Last version compatible with python 3.6
tuswsgi = "*"
typing-extensions = "*"
uvicorn = "*"
WebOb = "*"
Whoosh = "*"
zipstream-new = "*"

[tool.poetry.dev-dependencies]
cwltest = "2.2.20210901154959"
fluent-logger = "*"
gunicorn = "*"
httpx = "*"
lxml = "!=4.2.2"
markdown-it-reporter = "*"
NoseHTML = "*"
PyGithub = "*"
pytest = "*"
pytest-asyncio = "*"
pytest-celery = "*"
pytest-cov = "*"
pytest-html = "*"
python-irodsclient = "*"
pytest-json-report = "*"
pytest-mock = "*"
pytest-pythonpath = "*"
pytest-postgresql = "!=3.0.0"  # https://github.com/ClearcodeHQ/pytest-postgresql/issues/426
pytest-shard = "*"
recommonmark = "*"
responses = "*"
selenium = "*"
Sphinx = ">=4.0"  # support docutils 0.17
sphinx_markdown_tables = "*"
sphinx_rtd_theme = "*"
statsd = "*"
testfixtures = "*"
tuspy = "*"
twill = "*"
watchdog = "*"
