from typing import TypeAlias

from .file_pattern_dataset_collection_description import FilePatternDatasetCollectionDescription
from .tool_provided_metadata_dataset_collection import ToolProvidedMetadataDatasetCollection

__all__ = ["AnonymousArrayItem4"]

AnonymousArrayItem4: TypeAlias = FilePatternDatasetCollectionDescription | ToolProvidedMetadataDatasetCollection
