from typing import TypeAlias

from .update_dataset_permissions_payload import UpdateDatasetPermissionsPayload
from .update_dataset_permissions_payload_alias_b import UpdateDatasetPermissionsPayloadAliasB
from .update_dataset_permissions_payload_alias_c import UpdateDatasetPermissionsPayloadAliasC

__all__ = ["HistoriesContentsPermissionsUpdatePermissionsRequestBody"]

HistoriesContentsPermissionsUpdatePermissionsRequestBody: TypeAlias = (
    UpdateDatasetPermissionsPayload | UpdateDatasetPermissionsPayloadAliasB | UpdateDatasetPermissionsPayloadAliasC
)
