from dataclasses import dataclass

__all__ = ["InputStep"]


@dataclass
class InputStep:
    """
    InputStep dataclass

    Args:
        source_step (int)        : The identifier of the workflow step connected to this
                                   particular input.
        step_output (str)        : The name of the output generated by the source step.
    """

    source_step: int  # The identifier of the workflow step connected to this particular input.
    step_output: str  # The name of the output generated by the source step.

    class Meta:
        """Configure field name mapping for JSON conversion."""

        key_transform_with_load = {
            "source_step": "source_step",
            "step_output": "step_output",
        }
        key_transform_with_dump = {
            "source_step": "source_step",
            "step_output": "step_output",
        }
