from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

T = TypeVar("T", bound="InputStep")


@_attrs_define
class InputStep:
    """
    Attributes:
        source_step (int): The identifier of the workflow step connected to this particular input.
        step_output (str): The name of the output generated by the source step.
    """

    source_step: int
    step_output: str
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        source_step = self.source_step

        step_output = self.step_output

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "source_step": source_step,
                "step_output": step_output,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        source_step = d.pop("source_step")

        step_output = d.pop("step_output")

        input_step = cls(
            source_step=source_step,
            step_output=step_output,
        )

        input_step.additional_properties = d
        return input_step

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
