from dataclasses import dataclass

__all__ = ["InputStep"]


@dataclass
class InputStep:
    """
    InputStep dataclass.

    Args:
        source_step (int)        : The identifier of the workflow step connected to this
                                   particular input.
        step_output (str)        : The name of the output generated by the source step.
    """

    source_step: int  # The identifier of the workflow step connected to this particular input.
    step_output: str  # The name of the output generated by the source step.
