from typing import TypeAlias

from .invocation_cancellation_history_deleted_response import InvocationCancellationHistoryDeletedResponse
from .invocation_cancellation_review_failed_response import InvocationCancellationReviewFailedResponse
from .invocation_cancellation_user_request_response import InvocationCancellationUserRequestResponse
from .invocation_evaluation_warning_workflow_output_not_found_response import (
    InvocationEvaluationWarningWorkflowOutputNotFoundResponse,
)
from .invocation_failure_collection_failed_response import InvocationFailureCollectionFailedResponse
from .invocation_failure_dataset_failed_response import InvocationFailureDatasetFailedResponse
from .invocation_failure_expression_evaluation_failed_response import (
    InvocationFailureExpressionEvaluationFailedResponse,
)
from .invocation_failure_job_failed_response import InvocationFailureJobFailedResponse
from .invocation_failure_output_not_found_response import InvocationFailureOutputNotFoundResponse
from .invocation_failure_when_not_boolean_response import InvocationFailureWhenNotBooleanResponse
from .invocation_failure_workflow_parameter_invalid_response import InvocationFailureWorkflowParameterInvalidResponse
from .invocation_unexpected_failure_response import InvocationUnexpectedFailureResponse

__all__ = ["InvocationMessageResponseUnion"]

InvocationMessageResponseUnion: TypeAlias = (
    InvocationCancellationHistoryDeletedResponse
    | InvocationCancellationReviewFailedResponse
    | InvocationCancellationUserRequestResponse
    | InvocationEvaluationWarningWorkflowOutputNotFoundResponse
    | InvocationFailureCollectionFailedResponse
    | InvocationFailureDatasetFailedResponse
    | InvocationFailureExpressionEvaluationFailedResponse
    | InvocationFailureJobFailedResponse
    | InvocationFailureOutputNotFoundResponse
    | InvocationFailureWhenNotBooleanResponse
    | InvocationFailureWorkflowParameterInvalidResponse
    | InvocationUnexpectedFailureResponse
)
