from typing import TypeAlias

from .parsed_fetch_workbook_for_collections import ParsedFetchWorkbookForCollections
from .parsed_fetch_workbook_for_datasets import ParsedFetchWorkbookForDatasets

__all__ = ["ToolsFetchWorkbookParse200Response"]

ToolsFetchWorkbookParse200Response: TypeAlias = ParsedFetchWorkbookForDatasets | ParsedFetchWorkbookForCollections
