"""Constants shared by job setup and external metadata workers."""

LAZY_IMPORTS_ENV = "GALAXY_SET_METADATA_LAZY_IMPORTS"
LIGHTWEIGHT_MODELS_ENV = "GALAXY_SET_METADATA_LIGHTWEIGHT_MODELS"
PYDANTIC_DISABLE_PLUGINS_ENV = "PYDANTIC_DISABLE_PLUGINS"
TOOL_PROVIDED_JOB_METADATA_FILE = "galaxy.json"
TOOL_PROVIDED_JOB_METADATA_KEYS = ["name", "info", "dbkey", "created_from_basename"]

__all__ = (
    "LAZY_IMPORTS_ENV",
    "LIGHTWEIGHT_MODELS_ENV",
    "PYDANTIC_DISABLE_PLUGINS_ENV",
    "TOOL_PROVIDED_JOB_METADATA_FILE",
    "TOOL_PROVIDED_JOB_METADATA_KEYS",
)
