name: Integration Selenium
on: [push, pull_request]
env:
  GALAXY_CONFIG_OVERRIDE_METADATA_STRATEGY: 'extended'
  GALAXY_CONFIG_OVERRIDE_OUTPUTS_TO_WORKING_DIRECTORY: 'true'
  GALAXY_SKIP_CLIENT_BUILD: '0'
  GALAXY_TEST_DBURI: 'postgresql://postgres:postgres@localhost:5432/galaxy?client_encoding=utf8'
  GALAXY_TEST_RAISE_EXCEPTION_ON_HISTORYLESS_HDA: '1'
  GALAXY_TEST_SELENIUM_RETRIES: 1
  YARN_INSTALL_OPTS: --frozen-lockfile
concurrency:
  group: integration-selenium-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: ['3.7']
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - name: Prune unused docker image, volumes and containers
        run: docker system prune -a -f
      - uses: actions/checkout@v2
        with:
          path: 'galaxy root'
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip dir
        uses: actions/cache@v1
        id: pip-cache
        with:
          path: ~/.cache/pip
          key: pip-cache-${{ matrix.python-version }}-${{ hashFiles('galaxy root/requirements.txt') }}
      - uses: mvdbeek/gha-yarn-cache@master
        with:
          yarn-lock-file: 'galaxy root/client/yarn.lock'
      - uses: nanasess/setup-chromedriver@master
      - name: Run tests
        run: './run_tests.sh -integration test/integration_selenium'
        working-directory: 'galaxy root'
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Integration Selenium test results (${{ matrix.python-version }})
          path: 'galaxy root/run_integration_tests.html'
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Integration Selenium debug info (${{ matrix.python-version }})
          path: 'galaxy root/database/test_errors'
