name: Python linting
on:
  push:
    paths:
      - '**.py'
      - '.github/workflows/lint.yaml'
      - lib/galaxy/dependencies/**
      - mypy.ini
  pull_request:
    paths:
      - '**.py'
      - '.github/workflows/lint.yaml'
      - lib/galaxy/dependencies/**
      - mypy.ini
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.11']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Get full Python version
        id: full-python-version
        shell: bash
        run: echo "version=$(python -c 'import sys; print("-".join(str(v) for v in sys.version_info))')" >> $GITHUB_OUTPUT
      - name: Cache pip dir
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-cache-${{ matrix.python-version }}-${{ hashFiles('lib/galaxy/dependencies/pinned-lint-requirements.txt') }}
      - name: Cache tox env
        uses: actions/cache@v3
        with:
          path: .tox
          key: tox-cache-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('lib/galaxy/dependencies/pinned-lint-requirements.txt') }}-lint
      - name: Install tox
        run: pip install tox
      - name: Run linting
        run: tox -e lint
      - name: Run docstring linting
        run: tox -e lint_docstring_include_list
      - name: Run mypy checks
        run: tox -e mypy
      - uses: psf/black@stable
      - uses: isort/isort-action@master
